name: bart-0.3.0
channels:
  - conda-forge
dependencies:
  - blas
  - jupyter
  - scikit-learn
  - pip
  - pre-commit
  - python=3.9
  - pymc==5.0.1
  - arviz==0.13.0
  - snakeviz
  - pip:
    - argparse==1.4.0
    - matplotlib==3.5.2
    - memory-profiler==0.61.0
    - pymc-bart==0.3.0
    - snakeviz==2.1.1
